SmashCharacters = [
    {'id': 'koopa', 'name': 'Bowser'},
    {'id': 'koopajr', 'name': 'Bowser Jr.'},
    {'id': 'koopajr', 'name': 'larry'},
    {'id': 'koopajr', 'name': 'roy'},
    {'id': 'koopajr', 'name': 'wendy'},
    {'id': 'koopajr', 'name': 'iggy'},
    {'id': 'koopajr', 'name': 'morton'},
    {'id': 'koopajr', 'name': 'lemmy'},
    {'id': 'koopajr', 'name': 'ludwig'},
    {'id': 'captain', 'name': 'CFalcon'},
    {'id': 'captain', 'name': 'CaptainFalcon'},
    {'id': 'lizardon', 'name': 'Charizard'},
    {'id': 'diddy', 'name': 'Diddy Kong'},
    {'id': 'diddy', 'name': 'Diddy'},
    {'id': 'donkey', 'name': 'DK'},
    {'id': 'donkey', 'name': 'Donkey Kong'},
    {'id': 'donkey', 'name': 'DKong'},
    {'id': 'pitb', 'name': 'Dark Pit'},
     {'id': 'pitb', 'name': 'DPit'},
    {'id': 'drmario', 'name': 'Dr. Mario'},
    {'id': 'duckhunt', 'name': 'Duck Hunt'},
    {'id': 'falco', 'name': 'Falco'},
    {'id': 'fox', 'name': 'Fox'},
    {'id': 'ganon', 'name': 'Ganondorf'},
    {'id': 'ganon', 'name': 'Ganon'},
    {'id': 'gekkouga', 'name': 'Greninja'},
    {'id': 'ike', 'name': 'Ike'},
    {'id': 'dedede', 'name': 'King Dedede'},
    {'id': 'dedede', 'name': 'Dedede'},
    {'id': 'kirby', 'name': 'Kirby'},
    {'id': 'link', 'name': 'Link'},
    {'id': 'littlemac', 'name': 'Little Mac'},
    {'id': 'lucario', 'name': 'Lucario'},
    {'id': 'lucina', 'name': 'Lucina'},
    {'id': 'luigi', 'name': 'Luigi'},
    {'id': 'mario', 'name': 'Mario'},
    {'id': 'marth', 'name': 'Marth'},
    {'id': 'rockman', 'name': 'Megaman'},
    {'id': 'metaknight', 'name': 'Meta Knight'},
    {'id': 'mewtwo', 'name': 'Mewtwo'},
    {'id': 'miifighter', 'name': 'Mii Brawler'},
    {'id': 'miigunner', 'name': 'Mii Gunner'},
    {'id': 'miiswordsman', 'name': 'Mii Swordsman'},
    {'id': 'gamewatch', 'name': 'Mr. Game & Watch'},
    {'id': 'gamewatch', 'name': 'Mr. G&W'},
    {'id': 'ness', 'name': 'Ness'},
    {'id': 'pacman', 'name': 'Pacman'},
    {'id': 'palutena', 'name': 'Palutena'},
    {'id': 'peach', 'name': 'Peach'},
    {'id': 'pikachu', 'name': 'Pikachu'},
    {'id': 'pikmin', 'name': 'Olimar'},
    {'id': 'pikmin', 'name': 'captainOlimar'},
    {'id': 'pit', 'name': 'Pit'},
    {'id': 'purin', 'name': 'Jigglypuff'},
    {'id': 'omakase', 'name': 'Random'},
    {'id': 'reflet', 'name': 'Robin'},
    {'id': 'robot', 'name': 'ROB'},
    {'id': 'robot', 'name': 'ROBOT'},
    {'id': 'rosetta', 'name': 'Rosalina'},
    {'id': 'rosetta', 'name': 'Rosalinaluma'},
    {'id': 'samus', 'name': 'Samus'},
    {'id': 'sheik', 'name': 'Sheik'},
    {'id': 'shulk', 'name': 'Shulk'},
    {'id': 'sonic', 'name': 'Sonic'},
    {'id': 'toonlink', 'name': 'Toon Link'},
    {'id': 'toonlink', 'name': 'TLink'},
    {'id': 'murabito', 'name': 'Villager'},
    {'id': 'wario', 'name': 'Wario'},
    {'id': 'wiifit', 'name': 'Wii Fit Trainer'},
    {'id': 'wiifit', 'name': 'Wii Fit'},
    {'id': 'yoshi', 'name': 'Yoshi'},
    {'id': 'zelda', 'name': 'Zelda'},
    {'id': 'szerosuit', 'name': 'Zero Suit Samus'},
    {'id': 'szerosuit', 'name': 'Zss'}
];

CharacterDict = _.reduce(SmashCharacters, function (tot, a) {
    tot[a.id] = a.name;
    return tot;
}, {});

ReverseCharacterDict = _.reduce(SmashCharacters, function (tot, a) {
    tot[a.name.replace(/\W/g, '').toLowerCase()] = a.id;
    return tot;
}, {});
