SmashCharacters = [
    {'id': 'koopa', 'name': 'Bowser', flipLeft: false, flipRight: true},
    {'id': 'koopajr', 'name': 'Bowser Jr.', flipLeft: false, flipRight: true},
    {'id': 'captain', 'name': 'Captain Falcon', flipLeft: false, flipRight: true},
    {'id': 'lizardon', 'name': 'Charizard', flipLeft: false, flipRight: true},
    {'id': 'diddy', 'name': 'Diddy Kong', flipLeft: false, flipRight: true},
    {'id': 'donkey', 'name': 'DK', flipLeft: false, flipRight: true},
    {'id': 'pitb', 'name': 'Dark Pit', flipLeft: false, flipRight: true},
    {'id': 'drmario', 'name': 'Dr. Mario', flipLeft: false, flipRight: true},
    {'id': 'duckhunt', 'name': 'Duck Hunt', flipLeft: false, flipRight: true},
    {'id': 'falco', 'name': 'Falco', flipLeft: false, flipRight: true},
    {'id': 'fox', 'name': 'Fox', flipLeft: false, flipRight: true},
    {'id': 'ganon', 'name': 'Ganondorf', flipLeft: false, flipRight: true},
    {'id': 'gekkouga', 'name': 'Greninja', flipLeft: false, flipRight: true},
    {'id': 'ike', 'name': 'Ike', flipLeft: false, flipRight: true},
    {'id': 'dedede', 'name': 'King Dedede', flipLeft: false, flipRight: true},
    {'id': 'kirby', 'name': 'Kirby', flipLeft: false, flipRight: true},
    {'id': 'link', 'name': 'Link', flipLeft: false, flipRight: true},
    {'id': 'littlemac', 'name': 'Little Mac', flipLeft: false, flipRight: true},
    {'id': 'lucario', 'name': 'Lucario', flipLeft: false, flipRight: true},
    {'id': 'lucina', 'name': 'Lucina', flipLeft: false, flipRight: true},
    {'id': 'luigi', 'name': 'Luigi', flipLeft: false, flipRight: true},
    {'id': 'mario', 'name': 'Mario', flipLeft: false, flipRight: true},
    {'id': 'marth', 'name': 'Marth', flipLeft: false, flipRight: true},
    {'id': 'rockman', 'name': 'Megaman', flipLeft: false, flipRight: true},
    {'id': 'metaknight', 'name': 'Meta Knight', flipLeft: false, flipRight: true},
    {'id': 'mewtwo', 'name': 'Mewtwo', flipLeft: false, flipRight: true},
    {'id': 'miifighter', 'name': 'Mii Brawler', flipLeft: false, flipRight: true},
    {'id': 'miigunner', 'name': 'Mii Gunner', flipLeft: false, flipRight: true},
    {'id': 'miiswordsman', 'name': 'Mii Swordsman', flipLeft: false, flipRight: true},
    {'id': 'gamewatch', 'name': 'Mr. Game & Watch', flipLeft: false, flipRight: true},
    {'id': 'ness', 'name': 'Ness', flipLeft: false, flipRight: true},
    {'id': 'pacman', 'name': 'Pacman', flipLeft: false, flipRight: true},
    {'id': 'palutena', 'name': 'Palutena', flipLeft: false, flipRight: true},
    {'id': 'peach', 'name': 'Peach', flipLeft: false, flipRight: true},
    {'id': 'pikachu', 'name': 'Pikachu', flipLeft: false, flipRight: true},
    {'id': 'pikmin', 'name': 'Olimar', flipLeft: false, flipRight: true},
    {'id': 'pit', 'name': 'Pit', flipLeft: false, flipRight: true},
    {'id': 'purin', 'name': 'Jigglypuff', flipLeft: false, flipRight: true},
    {'id': 'omakase', 'name': 'Random', flipLeft: false, flipRight: true},
    {'id': 'reflet', 'name': 'Robin', flipLeft: false, flipRight: true},
    {'id': 'robot', 'name': 'ROB', flipLeft: false, flipRight: true},
    {'id': 'rosetta', 'name': 'Rosalina', flipLeft: false, flipRight: true},
    {'id': 'samus', 'name': 'Samus', flipLeft: false, flipRight: true},
    {'id': 'sheik', 'name': 'Sheik', flipLeft: false, flipRight: true},
    {'id': 'shulk', 'name': 'Shulk', flipLeft: false, flipRight: true},
    {'id': 'sonic', 'name': 'Sonic', flipLeft: false, flipRight: true},
    {'id': 'toonlink', 'name': 'Toon Link', flipLeft: false, flipRight: true},
    {'id': 'murabito', 'name': 'Villager', flipLeft: false, flipRight: true},
    {'id': 'wario', 'name': 'Wario', flipLeft: false, flipRight: true},
    {'id': 'wiifit', 'name': 'Wii Fit Trainer', flipLeft: false, flipRight: true},
    {'id': 'yoshi', 'name': 'Yoshi', flipLeft: false, flipRight: true},
    {'id': 'zelda', 'name': 'Zelda', flipLeft: false, flipRight: true},
    {'id': 'szerosuit', 'name': 'Zero Suit Samus', flipLeft: false, flipRight: true}
];