SmashCharacters = [
    {'id': 'captain', 'name': 'Captain Falcon'},
    {'id': 'dedede', 'name': 'King Dedede'},
    {'id': 'diddy', 'name': 'Diddy Kong'},
    {'id': 'donkey', 'name': 'DK'},
    {'id': 'drmario', 'name': 'Dr. Mario'},
    {'id': 'duckhunt', 'name': 'Duck Hunt'},
    {'id': 'falco', 'name': 'Falco'},
    {'id': 'fox', 'name': 'Fox'},
    {'id': 'gamewatch', 'name': 'Mr. Game & Watch'},
    {'id': 'ganon', 'name': 'Ganondorf'},
    {'id': 'gekkouga', 'name': 'Greninja'},
    {'id': 'ike', 'name': 'Ike'},
    {'id': 'kirby', 'name': 'Kirby'},
    {'id': 'koopa', 'name': 'Bowser'},
    {'id': 'koopajr', 'name': 'Bowser Jr.'},
    {'id': 'link', 'name': 'Link'},
    {'id': 'littlemac', 'name': 'Little Mac'},
    {'id': 'lizardon', 'name': 'Charizard'},
    {'id': 'lucario', 'name': 'Lucario'},
    {'id': 'lucina', 'name': 'Lucina'},
    {'id': 'luigi', 'name': 'Luigi'},
    {'id': 'mario', 'name': 'Mario'},
    {'id': 'marth', 'name': 'Marth'},
    {'id': 'metaknight', 'name': 'Meta Knight'},
    {'id': 'miifighter', 'name': 'Mii Brawler'},
    {'id': 'miigunner', 'name': 'Mii Gunner'},
    {'id': 'miiswordsman', 'name': 'Mii Swordsman'},
    {'id': 'murabito', 'name': 'Villager'},
    {'id': 'ness', 'name': 'Ness'},
    {'id': 'omakase', 'name': 'Random'},
    {'id': 'pacman', 'name': 'Pacman'},
    {'id': 'palutena', 'name': 'Palutena'},
    {'id': 'peach', 'name': 'Peach'},
    {'id': 'pikachu', 'name': 'Pikachu'},
    {'id': 'pikmin', 'name': 'Olimar'},
    {'id': 'pit', 'name': 'Pit'},
    {'id': 'pitb', 'name': 'Dark Pit'},
    {'id': 'purin', 'name': 'Jigglypuff'},
    {'id': 'reflet', 'name': 'Robin'},
    {'id': 'robot', 'name': 'ROB'},
    {'id': 'rockman', 'name': 'Megaman'},
    {'id': 'rosetta', 'name': 'Rosalina'},
    {'id': 'samus', 'name': 'Samus'},
    {'id': 'sheik', 'name': 'Sheik'},
    {'id': 'shulk', 'name': 'Shulk'},
    {'id': 'sonic', 'name': 'Sonic'},
    {'id': 'szerosuit', 'name': 'Zero Suit Samus'},
    {'id': 'toonlink', 'name': 'Toon Link'},
    {'id': 'wario', 'name': 'Wario'},
    {'id': 'wiifit', 'name': 'Wii Fit Trainer'},
    {'id': 'yoshi', 'name': 'Yoshi'},
    {'id': 'zelda', 'name': 'Zelda'},
    {'id': 'mewtwo', 'name': 'Mewtwo'}
];