MatchTypes = [
    { id: 'none', name: ''},
    { id: 'none', name: 'Pools'},
    { id: 'none', name: 'Money Match'},
    { id: 'wb', name: 'Winners Bracket'},
    { id: 'lb', name: 'Losers Bracket'},
    { id: 'gf', name: 'Grand Finals'},
    { id: 'wf', name: 'Winners Finals'},
    { id: 'lf', name: 'Losers Finals'},
    { id: 'w4', name: 'Winners Semis'},
    { id: 'l4', name: 'Losers Semis'},
    { id: 'w8', name: 'Winners Quarters'},
    { id: 'l8', name: 'Losers Quarters'},
    { id: 'w16', name: 'Winners Ro16'},
    { id: 'l16', name: 'Losers Ro16'},
    { id: 'w32', name: 'Winners Ro32'},
    { id: 'l32', name: 'Losers Ro32'},
    { id: 'w64', name: 'Winners Ro64'},
    { id: 'l64', name: 'Losers Ro64'},
    { id: 'w128', name: 'Winners Ro128'}
];
